/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistema.view;

import br.com.sistema.dao.VeiculoDAO;
import br.com.sistema.model.Veiculo;
import java.util.List;
import br.com.sistema.dao.ServicoDAO;
import br.com.sistema.model.Servico;
import java.math.BigDecimal;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GabrielHDias
 */
public class TelaServico extends javax.swing.JFrame {

    /**
     * Creates new form TelaServico
     */
    public TelaServico() {
        initComponents();
        carregarVeiculos();
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        cbVeiculo = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServicos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Cadastro de serviços");

        jLabel2.setText("Descrição");

        jLabel3.setText("Valor");

        jLabel4.setText("Data");

        jLabel5.setText("Veículo");

        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });

        cbVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        tblServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Descrição", "Valor", "Data", "Veículo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblServicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblServicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblServicos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValor)
                            .addComponent(txtDescricao)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbVeiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtData)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpar)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cbVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if (!validarCampos()) {
            return;
        }

        Servico servico = new Servico();

        servico.setDescricao(
                txtDescricao.getText().trim()
        );

        servico.setValor(
                new BigDecimal(
                        txtValor.getText().trim().replace(",", ".")
                )
        );

        servico.setDataServico(
                Date.valueOf(txtData.getText().trim())
        );

        servico.setVeiculoId(
                getVeiculoIdSelecionado()
        );

        ServicoDAO dao = new ServicoDAO();
        dao.salvar(servico);

        JOptionPane.showMessageDialog(
                this,
                "Serviço cadastrado com sucesso!"
        );

        atualizarTabela();
        limparCampos();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void tblServicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServicosMouseClicked

        int linha = tblServicos.getSelectedRow();

        if (linha != -1) {

            txtDescricao.setText(
                    tblServicos.getValueAt(linha, 1).toString()
            );

            txtValor.setText(
                    tblServicos.getValueAt(linha, 2).toString()
            );

            txtData.setText(
                    tblServicos.getValueAt(linha, 3).toString()
            );

            String descricaoVeiculo
                    = tblServicos.getValueAt(linha, 4).toString();

            for (int i = 0; i < cbVeiculo.getItemCount(); i++) {

                String item = cbVeiculo.getItemAt(i);

                if (item.endsWith(descricaoVeiculo)) {
                    cbVeiculo.setSelectedIndex(i);
                    break;
                }
            }
        }
    }//GEN-LAST:event_tblServicosMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        int linha = tblServicos.getSelectedRow();

        if (linha == -1) {

            JOptionPane.showMessageDialog(
                    this,
                    "Selecione um serviço na tabela."
            );

            return;
        }

        if (!validarCampos()) {
            return;
        }

        int id = Integer.parseInt(
                tblServicos.getValueAt(linha, 0).toString()
        );

        Servico servico = new Servico();

        servico.setId(id);

        servico.setDescricao(
                txtDescricao.getText().trim()
        );

        servico.setValor(
                new BigDecimal(
                        txtValor.getText().trim().replace(",", ".")
                )
        );

        servico.setDataServico(
                Date.valueOf(txtData.getText().trim())
        );

        servico.setVeiculoId(
                getVeiculoIdSelecionado()
        );

        ServicoDAO dao = new ServicoDAO();
        dao.editar(servico);

        JOptionPane.showMessageDialog(
                this,
                "Serviço editado com sucesso!"
        );

        atualizarTabela();
        limparCampos();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linha = tblServicos.getSelectedRow();

        if (linha == -1) {

            JOptionPane.showMessageDialog(
                    this,
                    "Selecione um serviço na tabela."
            );

            return;
        }

        int resposta = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente excluir este serviço?",
                "Confirmar exclusão",
                JOptionPane.YES_NO_OPTION
        );

        if (resposta == JOptionPane.YES_OPTION) {

            int id = Integer.parseInt(
                    tblServicos.getValueAt(linha, 0).toString()
            );

            ServicoDAO dao = new ServicoDAO();
            dao.excluir(id);

            JOptionPane.showMessageDialog(
                    this,
                    "Serviço excluído com sucesso!"
            );

            atualizarTabela();
            limparCampos();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed
    private void limparCampos() {

        txtDescricao.setText("");
        txtValor.setText("");
        txtData.setText("");

        cbVeiculo.setSelectedIndex(-1);
        tblServicos.clearSelection();

        txtDescricao.requestFocus();
    }

    private void atualizarTabela() {

        DefaultTableModel modelo
                = (DefaultTableModel) tblServicos.getModel();

        modelo.setRowCount(0);

        ServicoDAO dao = new ServicoDAO();
        List<Servico> servicos = dao.listar();

        for (Servico servico : servicos) {

            modelo.addRow(new Object[]{
                servico.getId(),
                servico.getDescricao(),
                servico.getValor(),
                servico.getDataServico(),
                getDescricaoVeiculo(servico.getVeiculoId())
            });
        }
    }

    private String getDescricaoVeiculo(int veiculoId) {

        VeiculoDAO dao = new VeiculoDAO();
        List<Veiculo> veiculos = dao.listar();

        for (Veiculo veiculo : veiculos) {

            if (veiculo.getId() == veiculoId) {

                return veiculo.getPlaca()
                        + " - "
                        + veiculo.getMarca()
                        + " "
                        + veiculo.getModelo();
            }
        }

        return "";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaServico().setVisible(true);
            }
        });
    }

    private void carregarVeiculos() {

        cbVeiculo.removeAllItems();

        VeiculoDAO dao = new VeiculoDAO();
        List<Veiculo> veiculos = dao.listar();

        for (Veiculo veiculo : veiculos) {

            cbVeiculo.addItem(
                    veiculo.getId()
                    + " - "
                    + veiculo.getPlaca()
                    + " - "
                    + veiculo.getMarca()
                    + " "
                    + veiculo.getModelo()
            );
        }

        cbVeiculo.setSelectedIndex(-1);
    }

    private int getVeiculoIdSelecionado() {

        String item = cbVeiculo.getSelectedItem().toString();

        String[] partes = item.split(" - ", 2);

        return Integer.parseInt(partes[0]);
    }

    private boolean validarCampos() {

        String descricao = txtDescricao.getText().trim();
        String valorTexto = txtValor.getText().trim();
        String dataTexto = txtData.getText().trim();

        if (descricao.isEmpty()
                || valorTexto.isEmpty()
                || dataTexto.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Preencha todos os campos."
            );

            return false;
        }

        if (descricao.length() < 3) {

            JOptionPane.showMessageDialog(
                    this,
                    "A descrição deve possuir pelo menos 3 caracteres."
            );

            txtDescricao.requestFocus();
            return false;
        }

        try {

            BigDecimal valor
                    = new BigDecimal(valorTexto.replace(",", "."));

            if (valor.compareTo(BigDecimal.ZERO) <= 0) {

                JOptionPane.showMessageDialog(
                        this,
                        "O valor deve ser maior que zero."
                );

                txtValor.requestFocus();
                return false;
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Informe um valor válido."
            );

            txtValor.requestFocus();
            return false;
        }

        try {

            Date.valueOf(dataTexto);

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Data inválida.\nUse o formato AAAA-MM-DD."
            );

            txtData.requestFocus();
            return false;
        }

        if (cbVeiculo.getSelectedIndex() == -1) {

            JOptionPane.showMessageDialog(
                    this,
                    "Selecione um veículo."
            );

            cbVeiculo.requestFocus();
            return false;
        }

        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblServicos;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
